package com.gh0u1l5.wechatmagician.backend

import com.gh0u1l5.wechatmagician.backend.plugins.*

/**
 * Dynamically generated by build.gradle
 */
object WechatPlugins {
    fun list() = listOf(AntiRevoke, AdBlock, Developer, Donate, ObjectsHunter, SecretFriend, AutoLogin, ChatroomHider, Alert, MarkAllAsRead, AntiSnsDelete, Limits, SnsBlock, SnsForward)
}
