package com.gh0u1l5.wechatmagician.backend

import com.gh0u1l5.wechatmagician.backend.plugins.*

/**
 * Dynamically generated by build.gradle
 */
val WechatPlugins = listOf(AdBlock, Alert, AntiRevoke, AntiSnsDelete, AutoLogin, ChatroomHider, Developer, Donate, Limits, MarkAllAsRead, ObjectsHunter, SecretFriend, SnsBlock, SnsForward)
